name: Semgrep

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep CE
    if: ${{ (!github.event.repository.private || vars.ENABLE_GITHUB_CODE_SCANNING == 'true') && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep CE
        run: semgrep scan --config auto --sarif --output semgrep.sarif

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
